services:
  backend:
    image: mm-backend:latest
    build: .
    command: ["/app/server"]
    ports:
      - "${PORT:-8080}:80"
    depends_on:
      - postgres
      - valkey
    env_file:
      - path: .env
        required: false
  postgres:
    image: postgres:18.1
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - type: bind
        source: ./db/CreateTables.sql
        target: /docker-entrypoint-initdb.d/CreateTables.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "1301:5432"
    env_file:
      - path: .env
        required: false

  valkey:
    image: valkey/valkey:8
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "1302:6379"
    env_file:
      - path: .env
        required: false
