services:
  backend:
    build: .
    command: ["/app/server"]
    ports:
      - "${PORT:-8080}:80"
    depends_on:
      - db
      - dragonfly
    env_file:
      - .env

  backend-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "${PORT:-8080}:80"
    depends_on:
      - db
      - dragonfly
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /app

  db:
    image: postgres:17-alpine
    healthcheck:
      test: "pg_isready --username=${DB_USER:-sguhack} --database=${DB_NAME:-sguhack}"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - type: bind
        source: ./db/CreateTables.sql
        target: /docker-entrypoint-initdb.d/CreateTables.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    env_file:
      - .env

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    env_file:
      - .env
