definitions:
  apierr.ApiError:
    properties:
      error:
        type: string
    type: object
  blocks.SwaggerBlockType:
    description: For swagger use only. Use BlockType instead
    properties:
      blockType:
        type: string
      courseId:
        type: string
      data:
        type: object
      id:
        type: string
    required:
    - blockType
    - courseId
    - data
    - id
    type: object
  blocks.SwaggerCreateBlockType:
    description: For swagger use only. Use CreateBlockType instead
    properties:
      blockType:
        type: string
      data: {}
    required:
    - blockType
    - data
    type: object
  courses.CourseType:
    properties:
      createdAt:
        type: string
      disciplineId:
        type: string
      id:
        type: string
      name:
        type: string
      ownerId:
        type: string
    required:
    - createdAt
    - id
    - name
    - ownerId
    type: object
  courses.CreateCourseType:
    properties:
      disciplineId:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  courses.UpdateCourseType:
    properties:
      name:
        type: string
      ownerId:
        type: string
    type: object
  disciplines.CreateDisciplineType:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  disciplines.DisciplineType:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
  routes.LoginModel:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  routes.LoginSuccessResponse:
    properties:
      status:
        type: string
    type: object
  routes.RegisterModel:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    - username
    type: object
  user.OutModel:
    properties:
      avatarUrl:
        type: string
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      patronymic:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /blocks/:id:
    delete:
      description: Will remove block from course but won't delete it from database
      parameters:
      - description: Block ID
        in: path
        name: blockId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Block not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Remove block
      tags:
      - blocks
    get:
      description: Get block data
      parameters:
      - description: Block ID
        in: path
        name: blockId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/blocks.SwaggerBlockType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Block not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Get block data
      tags:
      - blocks
    patch:
      consumes:
      - application/json
      description: Change single or multiple parameters of the block
      parameters:
      - description: Block ID
        in: path
        name: blockId
        required: true
        type: integer
      - description: Block payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/blocks.SwaggerCreateBlockType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blocks.SwaggerBlockType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Block not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Modify block
      tags:
      - blocks
  /courses:
    get:
      description: From course list get page of limited number of courses with custom
        offset
      parameters:
      - description: Number of courses on the page
        in: query
        name: limit
        required: true
        type: integer
      - description: List offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/courses.CourseType'
        "400":
          description: Invalid limit or offset
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Courses not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Get course list page
      tags:
      - courses
  /courses/:
    post:
      consumes:
      - application/json
      description: Create new course
      parameters:
      - description: Course payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/courses.CreateCourseType'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/courses.CourseType'
        "400":
          description: Invalid JSON
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "403":
          description: No permission
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Create new course
      tags:
      - courses
  /courses/:id:
    delete:
      description: Will permanently delete course
      parameters:
      - description: Course ID
        in: path
        name: courseId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Course not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Delete course
      tags:
      - courses
    get:
      description: Get course data
      parameters:
      - description: Course ID
        in: path
        name: courseId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/courses.CourseType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Course not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Get course data
      tags:
      - courses
    patch:
      consumes:
      - application/json
      description: Change single or multiple parameters of the course
      parameters:
      - description: Course ID
        in: path
        name: courseId
        required: true
        type: integer
      - description: Course payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/courses.UpdateCourseType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/courses.CourseType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Course not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Modify course
      tags:
      - courses
  /courses/{course_id}/blocks:
    get:
      description: Get all blocks related to course
      parameters:
      - description: Course ID
        in: path
        name: courseId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/blocks.SwaggerBlockType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Block not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Get All block data
      tags:
      - blocks
    post:
      consumes:
      - application/json
      description: Add new block
      parameters:
      - description: Course ID
        in: path
        name: courseId
        required: true
        type: integer
      - description: Block payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/blocks.SwaggerCreateBlockType'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/blocks.SwaggerBlockType'
        "400":
          description: Invalid JSON
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "403":
          description: No permission
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Add new block
      tags:
      - blocks
  /disciplines/:
    post:
      consumes:
      - application/json
      description: Create new discipline
      parameters:
      - description: Discipline payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/disciplines.CreateDisciplineType'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/disciplines.DisciplineType'
        "400":
          description: Invalid JSON
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "403":
          description: No permission
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Create new discipline
      tags:
      - disciplines
  /disciplines/:id:
    delete:
      description: Will permanently delete discipline
      parameters:
      - description: Discipline ID
        in: path
        name: disciplineId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Discipline not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Delete discipline
      tags:
      - disciplines
    get:
      description: Get discipline data
      parameters:
      - description: Discipline ID
        in: path
        name: disciplineId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/disciplines.DisciplineType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Discipline not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Get discipline data
      tags:
      - disciplines
    patch:
      consumes:
      - application/json
      description: Change single or multiple parameters of the discipline
      parameters:
      - description: Discipline ID
        in: path
        name: disciplineId
        required: true
        type: integer
      - description: Discipline payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/disciplines.CreateDisciplineType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/disciplines.DisciplineType'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: Discipline not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Modify discipline
      tags:
      - disciplines
  /login:
    post:
      consumes:
      - application/json
      description: Login into account
      parameters:
      - description: Login data for some shit
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.LoginModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.LoginSuccessResponse'
        "400":
          description: Invalid JsOn
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "401":
          description: Wrong credentials
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Login into account
      tags:
      - auth
  /logout:
    post:
      description: Logout from an account
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.LoginSuccessResponse'
        "401":
          description: Cookie not exists
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Logout from an account
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Register a new account
      parameters:
      - description: Register payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.RegisterModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.OutModel'
        "400":
          description: Invalid JSON
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "401":
          description: Wrong credentials
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Register a new account
      tags:
      - auth
  /session:
    get:
      description: Get active session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.OutModel'
        "401":
          description: User not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/apierr.ApiError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/apierr.ApiError'
      summary: Get active session
      tags:
      - auth
swagger: "2.0"
